In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory



# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
#Saravana
rank_list = pd.read_csv('cleaned_rank_list.csv')
provisional_list = pd.read_csv('cleaned_prov_allot.csv')

In [5]:
rank_list_df = pd.DataFrame(rank_list)
provisonal_df = pd.DataFrame(provisional_list)

In [6]:
rank_list_df.head

<bound method NDFrame.head of       RANK    APPLN_NO NAME_OF_THE_CANDIDATE         DOB  GENDER  TANCET_MARK  \
0        1  3202410114               Ramya R  12-06-2000  FEMALE       99.965   
1        2  3202412138             DHARANI G  19-10-2002  FEMALE       99.954   
2        3  3202410032       MOHAN PRASATH S  30-04-2004    MALE       99.907   
3        4  3202410322        MANIKANDAN K S  06-02-2004    MALE       99.896   
4        5  3202411711          KALAIVANAN R  11-12-2003    MALE       99.838   
...    ...         ...                   ...         ...     ...          ...   
2468  2469  3202412150        DINESH KUMAR E  04-07-2003    MALE        0.301   
2469  2470  3202412047             VIGNESH M  04-06-2004    MALE        0.150   
2470  2471  3202412737               SUBHA M  28-10-1997  FEMALE        0.139   
2471  2472  3202411943            VIMALRAJ R  01-06-2004    MALE        0.058   
2472  2473  3202412719           SARUMATHI S  04-01-2004  FEMALE        0.012  

In [7]:
provisonal_df.head

<bound method NDFrame.head of       S NO    APPLN NO NAME OF THE CANDIDATE         DOB  GENDER COMMUNITY  \
0        1  3202410114               Ramya R  12-06-2000  FEMALE        OC   
1        2  3202412138             DHARANI G  19-10-2002  FEMALE       MBC   
2        3  3202410032       MOHAN PRASATH S  30-04-2004    MALE        BC   
3        4  3202410322        MANIKANDAN K S  06-02-2004    MALE        BC   
4        5  3202411711          KALAIVANAN R  11-12-2003    MALE        BC   
...    ...         ...                   ...         ...     ...       ...   
1661  1662  3202410338    Abdul Kalam Azad N  29-04-2004    MALE       BCM   
1662  1663  3202411568       SATHISH KUMAR S  28-04-2003    MALE       MBC   
1663  1664  3202412447         SURENDHIRAN A  01-01-2004    MALE       MBC   
1664  1665  3202412575  NAVANEETHAKRISHNAN V  31-12-2002    MALE        SC   
1665  1666  3202412036             SOWMIYA S  27-02-2004  FEMALE       MBC   

      TANCET\nMARK  RANK COLLEGE\

In [6]:
#I dont know what we can derive from this datasets, I just wanted to try how linear regressions and some other regressions works. 
#If you have any good idea with this, go on I'm in.

In [8]:
condition_value = 'OC'
new_value = 0
rank_list_df.loc[rank_list_df['COMMUNITY']==condition_value, 'COMMUNITY_RANK'] = new_value

In [9]:
X = rank_list_df[['TANCET_MARK', 'COMMUNITY']]
y = rank_list_df['COMMUNITY_RANK']

In [10]:
X = pd.get_dummies(X, columns=['COMMUNITY'])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
model = RandomForestClassifier()
param_grid = {'n_estimators': [100, 200, 300], 'max_depth': [10, 20, 30]}
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

C:\Users\renu4\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 30],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [14]:
best_model = grid_search.best_estimator_

In [15]:
y_pred = best_model.predict(X_test)

In [ ]:
#print(confusion_matrix(y_test, y_pred))
#print(classification_report(y_test, y_pred))

[[23  0  0 ...  0  0  0]
 [ 0  0  2 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        23
         4.0       0.00      0.00      0.00         2
         5.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         2
         7.0       0.00      0.00      0.00         1
         8.0       0.00      0.00      0.00         1
         9.0       0.00      0.00      0.00         2
        10.0       0.00      0.00      0.00         3
        11.0       0.00      0.00      0.00         1
        12.0       0.00      0.00      0.00         1
        13.0       0.00      0.00      0.00         2
        14.0       0.00      0.00      0.00         0
        16.0       0.00      0.00      0.00         1
        17.0       0.00      0.00      0.00         2
        19.0       0.00      0.00

C:\Users\renu4\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\renu4\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\renu4\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

In [20]:
def predict_new_data(new_data):
    """
    Predict the community rank for new input data.
    
    Parameters:
    new_data (pd.DataFrame): DataFrame containing new input data with the same structure as the original data.
    
    Returns:
    np.array: Predictions for the new input data.
    """
    # One-hot encode the new data
    new_data = pd.get_dummies(new_data, columns=['COMMUNITY'])
    
    # Align the new data with the columns of the training data
    new_data = new_data.reindex(columns=X.columns, fill_value=0)
    
    # Scale the new data
    new_data_scaled = scaler.transform(new_data)
    
    # Predict using the best model
    predictions = best_model.predict(new_data_scaled)
    
    return predictions

In [21]:
new_input_data = pd.DataFrame({
    'TANCET_MARK': [78.5, 85.0],
    'COMMUNITY': ['BC', 'MBC']
})

In [22]:
predictions = predict_new_data(new_input_data)
print(predictions)

[548. 143.]
